export { config } from './tamagui.config'
export { isWeb } from '@tamagui/core'
export * from './components'
export * from './validToken'
export * from 'tamagui'
export { LinearGradient } from 'tamagui/linear-gradient'
export * from '@tamagui/toast'
